List<Map<String, dynamic>> searchCases = [
  {
    "number": 0,
    "title": "[한글자막] 장송의 프리렌 op Full - 용사 / YOASOBI",
    "search_tag": [
      [
        "jangsongui peuriren op full",
        "yongsa",
        "yoasobi",
        "jangsongui",
        "peuriren",
        "op",
        "full",
        "dzb",
      ],
      [
        "funeral freelin op full",
        "hero",
        "yoasobi",
        "funeral",
        "freelin",
        "op",
        "full",
        "dzb",
      ],
      [
        "JNKSNKPRRNPFL",
        "ANKSNKPRRNPFL",
        "ANKS",
        "ANKS",
        "ASP",
        "ASP",
        "JNKSNK",
        "ANKSNK",
        "PRRN",
        "PRRN",
        "AP",
        "AP",
        "FL",
        "FL",
        "TSP",
        "TSP",
      ],
    ],
    "keywords": [
      "장송의 프리렌 op full",
      "용사",
      "yoasobi",
      "장송의",
      "프리렌",
      "op",
      "full",
      "dzb",
    ],
  },
  {
    "number": 1,
    "title": "비비디바 / 호시마치 스이세이 (공식)",
    "search_tag": [
      ["bibidiba", "hosimachi suisei", "gongsik", "hosimachi", "suisei", "dzb"],
      [
        "bibidiba",
        "hoshimachi suisei",
        "official",
        "hoshimachi",
        "suisei",
        "dzb",
      ],
      [
        "PPTP",
        "PPTP",
        "HSMXSS",
        "HSMKSS",
        "KNKSK",
        "KNKSK",
        "HSMX",
        "HSMK",
        "SS",
        "SS",
        "TSP",
        "TSP",
      ],
    ],
    "keywords": ["비비디바", "호시마치 스이세이", "공식", "호시마치", "스이세이", "dzb"],
  },
  {
    "number": 2,
    "title": "NEXT COLOR PLANET / 星街すいせい(official)",
    "search_tag": [
      [
        "next color planet",
        "hosimachi suisei",
        "next",
        "color",
        "planet",
        "dzb",
      ],
      [
        "next color planet",
        "hosimachi suisei",
        "next",
        "color",
        "planet",
        "dzb",
      ],
      [
        "NKSTKLRPLNT",
        "NKSTKLRPLNT",
        "HSMXSS",
        "HSMKSS",
        "NKST",
        "NKST",
        "KLR",
        "KLR",
        "PLNT",
        "PLNT",
        "TSP",
        "TSP",
      ],
    ],
    "keywords": [
      "next color planet",
      "星街すいせい",
      "next",
      "color",
      "planet",
      "dzb",
    ],
  },
  {
    "number": 3,
    "title": "YOASOBI「ラブレター」Official Music Video",
    "search_tag": [
      ["yoasobi", "raburetaa", "dzb"],
      ["yoasobi", "love letter", "dzb"],
      ["ASP", "ASP", "RPRT", "RPRT", "TSP", "TSP"],
    ],
    "keywords": ["yoasobi", "ラブレター", "dzb"],
  },
  {
    "number": 4,
    "title": "ソワレ / 星街すいせい(official)",
    "search_tag": [
      ["soware", "hoshimachi suisei", "dzb"],
      ["soiree", "hoshimachi suisei", "dzb"],
      ["SR", "SR", "HXMXSS", "HXMKSS", "TSP", "TSP"],
    ],
    "keywords": ["ソワレ", "星街すいせい", "dzb"],
  },
  {
    "number": 5,
    "title": "전방향 미소녀 (全方向美少女 ; noa) ／다즈비 COVER",
    "search_tag": [
      [
        "jeonbanghyang misonyeo",
        "zenzisukounobisyotyo",
        "noa",
        "dajeubi",
        "jeonbanghyang",
        "misonyeo",
        "dzb",
      ],
      [
        "all-direction beautiful girl",
        "all-direction beautiful girl",
        "noa",
        "dazbee",
        "all-direction",
        "beautiful girl",
        "dzb",
      ],
      [
        "JNPNKNKMSN",
        "ANPNKNKMSN",
        "SNSSKNPST",
        "SNTSSKNPST",
        "N",
        "N",
        "TJP",
        "TJP",
        "JNPNKNK",
        "ANPNKNK",
        "MSN",
        "MSN",
        "TSP",
        "TSP",
      ],
    ],
    "keywords": ["전방향 미소녀", "全方向美少女", "noa", "다즈비", "전방향", "미소녀", "dzb"],
  },
  {
    "number": 6,
    "title": "Aijanai",
    "search_tag": [
      ["aijanai", "dzb"],
      ["not love", "dzb"],
      ["AJN", "AHN", "TSP", "TSP"],
    ],
    "keywords": ["aijanai", "dzb"],
  },
  {
    "number": 7,
    "title": "Guitar, Loneliness and Blue Planet",
    "search_tag": [
      [
        "guitar loneliness and blue planet",
        "guitar",
        "loneliness",
        "and",
        "blue",
        "planet",
        "dzb",
      ],
      [
        "guitar loneliness and blue planet",
        "guitar",
        "loneliness",
        "and",
        "blue",
        "planet",
        "dzb",
      ],
      [
        "KTRLNLNSNTPLPLNT",
        "KTRLNLNSNTPLPLNT",
        "KTR",
        "KTR",
        "LNLNS",
        "LNLNS",
        "ANT",
        "ANT",
        "PL",
        "PL",
        "PLNT",
        "PLNT",
        "TSP",
        "TSP",
      ],
    ],
    "keywords": [
      "guitar loneliness and blue planet",
      "guitar",
      "loneliness",
      "and",
      "blue",
      "planet",
      "dzb",
    ],
  },
  {
    "number": 8,
    "title": "그래서 나는 음악을 그만두었다 (요루시카) ／다즈비 COVER",
    "search_tag": [
      [
        "geuraeseo naneun eumageul geumandueotda",
        "yorushika",
        "dajeubi",
        "geuraeseo",
        "naneun",
        "eumageul",
        "geumandueotda",
        "dzb",
      ],
      [
        "so i quit music",
        "yorushika",
        "dazbee",
        "so",
        "i",
        "quit",
        "music",
        "dzb",
      ],
      [
        "JRSNNNMJLJMNTT",
        "KRSNNNMKLKMNTT",
        "ARXK",
        "ARXK",
        "TJP",
        "TJP",
        "JRS",
        "KRS",
        "NNN",
        "NNN",
        "AMJL",
        "AMKL",
        "JMNTT",
        "KMNTT",
        "TSP",
        "TSP",
      ],
    ],
    "keywords": [
      "그래서 나는 음악을 그만두었다",
      "요루시카",
      "다즈비",
      "그래서",
      "나는",
      "음악을",
      "그만두었다",
      "dzb",
    ],
  },
];
